version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db_citytour
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bancoteste
      MYSQL_USER: developer
      MYSQL_PASSWORD: 741098
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql


  app:
    build: .
    container_name: api_citytour_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db_apicitytour?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  db_data: