version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db_citytour
    environment:
      POSTGRES_DB: db_apicitytour
      POSTGRES_USER: Developer
      POSTGRES_PASSWORD: developer
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: api_citytour_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_apicitytour
      SPRING_DATASOURCE_USERNAME: Developer
      SPRING_DATASOURCE_PASSWORD: developer
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

volumes:
  db_data: